import { interpolate } from "@/lib/i18n/interpolate";
import { parseProfileCardLocale } from "@/lib/profile-card/locale";
import type { Locale } from "@/lib/i18n/supported-locales";

export type ProfileCardCopy = {
  wrappedYear: string;
  yourYearOnGitHub: string;
  joinedYearsAgo: string;
  followedBy: string;
  publicRepos: string;
  totalContributions: string;
  streakWithRange: string;
  streakDays: string;
  projectOfTheYear: string;
  contributionsCount: string;
  noStandoutProject: string;
  mostActiveMonth: string;
  topLanguage: string;
  percentOfYear: string;
  languagesCount: string;
  activity: string;
  commits: string;
  prs: string;
  issues: string;
  reviews: string;
  repos: string;
  languages: string;
  orgs: string;
  mostActiveDay: string;
  activeDays: string;
  firstCommit: string;
  heatmap: string;
  footerLive: string;
  footerShare: string;
  yearOnly: string;
  markdownAlt: string;
};

const en: ProfileCardCopy = {
  wrappedYear: "Wrapped {year}",
  yourYearOnGitHub: "Your {year} on GitHub",
  joinedYearsAgo: "Joined {count}y ago",
  followedBy: "Followed by {count}",
  publicRepos: "{count} public repos",
  totalContributions: "Total contributions",
  streakWithRange: "Streak · {days} days · {range}",
  streakDays: "Streak · {days} days",
  projectOfTheYear: "Project of the year",
  contributionsCount: "{count} contributions",
  noStandoutProject: "No standout project yet",
  mostActiveMonth: "Most active month",
  topLanguage: "Top language",
  percentOfYear: "{percent}% of your year",
  languagesCount: "{count} languages",
  activity: "Activity",
  commits: "Commits",
  prs: "PRs",
  issues: "Issues",
  reviews: "Reviews",
  repos: "Repos",
  languages: "Languages",
  orgs: "Orgs",
  mostActiveDay: "Most active day",
  activeDays: "Active days",
  firstCommit: "First commit",
  heatmap: "{year} heatmap",
  footerLive: "This was your {year}. Keep shipping!",
  footerShare: "Share your year",
  yearOnly: "{year} only",
  markdownAlt: "@{username}'s Year on Git {year}",
};

const copies: Record<Locale, ProfileCardCopy> = {
  en,
  es: {
    wrappedYear: "Wrapped {year}",
    yourYearOnGitHub: "Tu {year} en GitHub",
    joinedYearsAgo: "Desde hace {count}a",
    followedBy: "Seguido por {count}",
    publicRepos: "{count} repos públicos",
    totalContributions: "Contribuciones totales",
    streakWithRange: "Racha · {days} días · {range}",
    streakDays: "Racha · {days} días",
    projectOfTheYear: "Proyecto del año",
    contributionsCount: "{count} contribuciones",
    noStandoutProject: "Aún no hay un proyecto destacado",
    mostActiveMonth: "Mes más activo",
    topLanguage: "Lenguaje principal",
    percentOfYear: "{percent}% de tu año",
    languagesCount: "{count} lenguajes",
    activity: "Actividad",
    commits: "Commits",
    prs: "PRs",
    issues: "Issues",
    reviews: "Reviews",
    repos: "Repos",
    languages: "Lenguajes",
    orgs: "Orgs",
    mostActiveDay: "Día más activo",
    activeDays: "Días activos",
    firstCommit: "Primer commit",
    heatmap: "Heatmap {year}",
    footerLive: "Este fue tu {year}. ¡Sigue creando!",
    footerShare: "Comparte tu año",
    yearOnly: "Solo {year}",
    markdownAlt: "Year on Git {year} de @{username}",
  },
  pt: {
    wrappedYear: "Wrapped {year}",
    yourYearOnGitHub: "Seu {year} no GitHub",
    joinedYearsAgo: "Entrou há {count}a",
    followedBy: "Seguido por {count}",
    publicRepos: "{count} repos públicos",
    totalContributions: "Contribuições totais",
    streakWithRange: "Sequência · {days} dias · {range}",
    streakDays: "Sequência · {days} dias",
    projectOfTheYear: "Projeto do ano",
    contributionsCount: "{count} contribuições",
    noStandoutProject: "Ainda sem um projeto de destaque",
    mostActiveMonth: "Mês mais ativo",
    topLanguage: "Linguagem principal",
    percentOfYear: "{percent}% do seu ano",
    languagesCount: "{count} linguagens",
    activity: "Atividade",
    commits: "Commits",
    prs: "PRs",
    issues: "Issues",
    reviews: "Reviews",
    repos: "Repos",
    languages: "Linguagens",
    orgs: "Orgs",
    mostActiveDay: "Dia mais ativo",
    activeDays: "Dias ativos",
    firstCommit: "Primeiro commit",
    heatmap: "Heatmap {year}",
    footerLive: "Esse foi o seu {year}. Continue enviando!",
    footerShare: "Compartilhe seu ano",
    yearOnly: "Somente {year}",
    markdownAlt: "Year on Git {year} de @{username}",
  },
  fr: {
    wrappedYear: "Wrapped {year}",
    yourYearOnGitHub: "Votre {year} sur GitHub",
    joinedYearsAgo: "Inscrit depuis {count} ans",
    followedBy: "Suivi par {count}",
    publicRepos: "{count} repos publics",
    totalContributions: "Contributions totales",
    streakWithRange: "Série · {days} jours · {range}",
    streakDays: "Série · {days} jours",
    projectOfTheYear: "Projet de l'année",
    contributionsCount: "{count} contributions",
    noStandoutProject: "Pas encore de projet phare",
    mostActiveMonth: "Mois le plus actif",
    topLanguage: "Langage principal",
    percentOfYear: "{percent}% de votre année",
    languagesCount: "{count} langages",
    activity: "Activité",
    commits: "Commits",
    prs: "PRs",
    issues: "Issues",
    reviews: "Reviews",
    repos: "Repos",
    languages: "Langages",
    orgs: "Orgs",
    mostActiveDay: "Jour le plus actif",
    activeDays: "Jours actifs",
    firstCommit: "Premier commit",
    heatmap: "Heatmap {year}",
    footerLive: "Voici votre {year}. Continuez d'avancer !",
    footerShare: "Partagez votre année",
    yearOnly: "{year} uniquement",
    markdownAlt: "Year on Git {year} de @{username}",
  },
  de: {
    wrappedYear: "Wrapped {year}",
    yourYearOnGitHub: "Dein {year} auf GitHub",
    joinedYearsAgo: "Dabei seit {count} J.",
    followedBy: "Gefolgt von {count}",
    publicRepos: "{count} öffentliche Repos",
    totalContributions: "Beiträge insgesamt",
    streakWithRange: "Serie · {days} Tage · {range}",
    streakDays: "Serie · {days} Tage",
    projectOfTheYear: "Projekt des Jahres",
    contributionsCount: "{count} Beiträge",
    noStandoutProject: "Noch kein herausragendes Projekt",
    mostActiveMonth: "Aktivster Monat",
    topLanguage: "Top-Sprache",
    percentOfYear: "{percent}% deines Jahres",
    languagesCount: "{count} Sprachen",
    activity: "Aktivität",
    commits: "Commits",
    prs: "PRs",
    issues: "Issues",
    reviews: "Reviews",
    repos: "Repos",
    languages: "Sprachen",
    orgs: "Orgs",
    mostActiveDay: "Aktivster Tag",
    activeDays: "Aktive Tage",
    firstCommit: "Erster Commit",
    heatmap: "Heatmap {year}",
    footerLive: "Das war dein {year}. Weiter so!",
    footerShare: "Teile dein Jahr",
    yearOnly: "Nur {year}",
    markdownAlt: "Year on Git {year} von @{username}",
  },
  it: {
    wrappedYear: "Wrapped {year}",
    yourYearOnGitHub: "Il tuo {year} su GitHub",
    joinedYearsAgo: "Iscritto da {count}a",
    followedBy: "Seguito da {count}",
    publicRepos: "{count} repo pubblici",
    totalContributions: "Contributi totali",
    streakWithRange: "Serie · {days} giorni · {range}",
    streakDays: "Serie · {days} giorni",
    projectOfTheYear: "Progetto dell'anno",
    contributionsCount: "{count} contributi",
    noStandoutProject: "Nessun progetto in evidenza",
    mostActiveMonth: "Mese più attivo",
    topLanguage: "Linguaggio principale",
    percentOfYear: "{percent}% del tuo anno",
    languagesCount: "{count} linguaggi",
    activity: "Attività",
    commits: "Commits",
    prs: "PRs",
    issues: "Issues",
    reviews: "Reviews",
    repos: "Repo",
    languages: "Linguaggi",
    orgs: "Org",
    mostActiveDay: "Giorno più attivo",
    activeDays: "Giorni attivi",
    firstCommit: "Primo commit",
    heatmap: "Heatmap {year}",
    footerLive: "Questo è stato il tuo {year}. Continua così!",
    footerShare: "Condividi il tuo anno",
    yearOnly: "Solo {year}",
    markdownAlt: "Year on Git {year} di @{username}",
  },
  ja: {
    wrappedYear: "Wrapped {year}",
    yourYearOnGitHub: "GitHubでの{year}",
    joinedYearsAgo: "{count}年前に参加",
    followedBy: "{count}人にフォロー",
    publicRepos: "公開リポジトリ {count}",
    totalContributions: "コントリビューション合計",
    streakWithRange: "連続 · {days}日 · {range}",
    streakDays: "連続 · {days}日",
    projectOfTheYear: "今年のプロジェクト",
    contributionsCount: "{count} コントリビューション",
    noStandoutProject: "目立ったプロジェクトはまだありません",
    mostActiveMonth: "最も活発な月",
    topLanguage: "トップ言語",
    percentOfYear: "年間の {percent}%",
    languagesCount: "{count} 言語",
    activity: "アクティビティ",
    commits: "Commits",
    prs: "PRs",
    issues: "Issues",
    reviews: "Reviews",
    repos: "Repos",
    languages: "言語",
    orgs: "Orgs",
    mostActiveDay: "最も活発な曜日",
    activeDays: "アクティブ日数",
    firstCommit: "最初のコミット",
    heatmap: "{year} のヒートマップ",
    footerLive: "これがあなたの{year}。これからも ship しよう！",
    footerShare: "今年をシェア",
    yearOnly: "{year} のみ",
    markdownAlt: "@{username} の Year on Git {year}",
  },
  zh: {
    wrappedYear: "Wrapped {year}",
    yourYearOnGitHub: "你的 {year} GitHub",
    joinedYearsAgo: "{count} 年前加入",
    followedBy: "{count} 人关注",
    publicRepos: "{count} 个公开仓库",
    totalContributions: "总贡献",
    streakWithRange: "连续 · {days} 天 · {range}",
    streakDays: "连续 · {days} 天",
    projectOfTheYear: "年度项目",
    contributionsCount: "{count} 次贡献",
    noStandoutProject: "还没有突出的项目",
    mostActiveMonth: "最活跃的月份",
    topLanguage: "主要语言",
    percentOfYear: "占全年的 {percent}%",
    languagesCount: "{count} 种语言",
    activity: "动态",
    commits: "Commits",
    prs: "PRs",
    issues: "Issues",
    reviews: "Reviews",
    repos: "Repos",
    languages: "语言",
    orgs: "Orgs",
    mostActiveDay: "最活跃的一天",
    activeDays: "活跃天数",
    firstCommit: "首次提交",
    heatmap: "{year} 热力图",
    footerLive: "这就是你的 {year}。继续前进！",
    footerShare: "分享你的一年",
    yearOnly: "仅 {year}",
    markdownAlt: "@{username} 的 Year on Git {year}",
  },
  ko: {
    wrappedYear: "Wrapped {year}",
    yourYearOnGitHub: "GitHub에서의 {year}",
    joinedYearsAgo: "{count}년 전 가입",
    followedBy: "{count}명이 팔로우",
    publicRepos: "공개 저장소 {count}개",
    totalContributions: "총 기여",
    streakWithRange: "연속 · {days}일 · {range}",
    streakDays: "연속 · {days}일",
    projectOfTheYear: "올해의 프로젝트",
    contributionsCount: "기여 {count}회",
    noStandoutProject: "아직 돋보이는 프로젝트가 없습니다",
    mostActiveMonth: "가장 활발한 달",
    topLanguage: "주요 언어",
    percentOfYear: "한 해의 {percent}%",
    languagesCount: "언어 {count}개",
    activity: "활동",
    commits: "Commits",
    prs: "PRs",
    issues: "Issues",
    reviews: "Reviews",
    repos: "Repos",
    languages: "언어",
    orgs: "Orgs",
    mostActiveDay: "가장 활발한 요일",
    activeDays: "활동일",
    firstCommit: "첫 커밋",
    heatmap: "{year} 히트맵",
    footerLive: "이것이 당신의 {year}입니다. 계속 나아가세요!",
    footerShare: "올해를 공유하세요",
    yearOnly: "{year}만",
    markdownAlt: "@{username}의 Year on Git {year}",
  },
  ar: {
    wrappedYear: "Wrapped {year}",
    yourYearOnGitHub: "{year} على GitHub",
    joinedYearsAgo: "انضم منذ {count} سنة",
    followedBy: "يتابعه {count}",
    publicRepos: "{count} مستودع عام",
    totalContributions: "إجمالي المساهمات",
    streakWithRange: "سلسلة · {days} يومًا · {range}",
    streakDays: "سلسلة · {days} يومًا",
    projectOfTheYear: "مشروع العام",
    contributionsCount: "{count} مساهمة",
    noStandoutProject: "لا يوجد مشروع بارز بعد",
    mostActiveMonth: "أكثر شهر نشاطًا",
    topLanguage: "اللغة الأبرز",
    percentOfYear: "{percent}% من عامك",
    languagesCount: "{count} لغات",
    activity: "النشاط",
    commits: "Commits",
    prs: "PRs",
    issues: "Issues",
    reviews: "Reviews",
    repos: "Repos",
    languages: "اللغات",
    orgs: "Orgs",
    mostActiveDay: "أكثر يوم نشاطًا",
    activeDays: "أيام النشاط",
    firstCommit: "أول commit",
    heatmap: "خريطة {year}",
    footerLive: "هذا كان عامك {year}. واصل الإنجاز!",
    footerShare: "شارك عامك",
    yearOnly: "{year} فقط",
    markdownAlt: "Year on Git {year} لـ @{username}",
  },
};

export function getProfileCardCopy(locale?: string | null): ProfileCardCopy {
  const resolved = parseProfileCardLocale(locale);
  return copies[resolved] ?? en;
}

export function profileCardText(
  copy: ProfileCardCopy,
  key: keyof ProfileCardCopy,
  values?: Record<string, string | number>,
): string {
  const template = copy[key] || en[key];
  return values ? interpolate(template, values) : template;
}
