export const LANGUAGE_ICON_SLUGS: Record<string, string> = {
  javascript: "javascript",
  typescript: "typescript",
  python: "python",
  java: "java",
  "c++": "cplusplus",
  c: "c",
  "c#": "csharp",
  php: "php",
  ruby: "ruby",
  go: "go",
  rust: "rust",
  swift: "swift",
  kotlin: "kotlin",
  dart: "dart",
  html: "html5",
  css: "css",
  shell: "gnubash",
  bash: "gnubash",
  powershell: "powershell",
  "objective-c": "apple",
  scala: "scala",
  r: "r",
  perl: "perl",
  lua: "lua",
  haskell: "haskell",
  elixir: "elixir",
  clojure: "clojure",
  julia: "julia",
  matlab: "mathworks",
  groovy: "apachegroovy",
  vue: "vuedotjs",
  "jupyter notebook": "jupyter",
  dockerfile: "docker",
  "vim script": "vim",
  viml: "vim",
  solidity: "solidity",
  zig: "zig",
  nim: "nim",
  crystal: "crystal",
  ocaml: "ocaml",
  "f#": "fsharp",
  erlang: "erlang",
  coffeescript: "coffeescript",
  scss: "sass",
  sass: "sass",
  less: "less",
  graphql: "graphql",
  yaml: "yaml",
  json: "json",
  markdown: "markdown",
  makefile: "gnu",
  "c# script": "csharp",
  "objective-c++": "apple",
  "visual basic .net": "visualstudio",
  "visual basic": "visualstudio",
  jupyter: "jupyter",
  docker: "docker",
  svelte: "svelte",
  angular: "angular",
  react: "react",
  "react native": "react",
  nextjs: "nextdotjs",
  "next.js": "nextdotjs",
  astro: "astro",
  terraform: "terraform",
  hcl: "hashicorp",
  nix: "nixos",
  ziglang: "zig",
  webassembly: "webassembly",
  wasm: "webassembly",
  sql: "postgresql",
  plsql: "oracle",
  tsql: "microsoftsqlserver",
  "emacs lisp": "gnuemacs",
  "common lisp": "lisp",
  scheme: "scheme",
  racket: "racket",
  fortran: "fortran",
  cobol: "cobol",
  pascal: "pascal",
  delphi: "delphi",
  ada: "ada",
  prolog: "prolog",
  smalltalk: "smalltalk",
  tcl: "tcl",
  awk: "awklanguage",
  cmake: "cmake",
  batchfile: "windows",
  tex: "latex",
  bibtex: "latex",
  handlebars: "handlebarsdotjs",
  mustache: "mustache",
  jinja: "jinja",
  twig: "symfony",
  ejs: "ejs",
  pug: "pug",
  stylus: "stylus",
  postcss: "postcss",
};

export const FALLBACK_ICON_SLUGS: Record<string, string> = {
  blade: "laravel",
  "blade template": "laravel",
  assembly: "gnometerminal",
  jinja2: "jinja",
  smarty: "php",
  hack: "facebook",
  reason: "reason",
  rescript: "rescript",
  purescript: "purescript",
  lean: "leanpub",
  qml: "qt",
  qmake: "qt",
  processing: "processingfoundation",
  gdscript: "godotengine",
  godot: "godotengine",
  hlsl: "directx",
  glsl: "opengl",
  wgsl: "webgpu",
  metal: "apple",
  shaderlab: "unity",
  "unity3d asset": "unity",
  "unreal script": "unrealengine",
  robotframework: "robotframework",
  gherkin: "cucumber",
  cucumber: "cucumber",
  starlark: "bazel",
  bazel: "bazel",
  thrift: "apachethrift",
  "protocol buffer": "protocolbuffers",
  protobuf: "protocolbuffers",
  "cap'n proto": "capnproto",
  apacheconf: "apache",
  nginx: "nginx",
  procfile: "heroku",
  gitignore: "git",
  gitattributes: "git",
  editorconfig: "editorconfig",
  dotenv: "dotenv",
  env: "dotenv",
};

const CDN_BASE =
  "https://cdn.jsdelivr.net/npm/simple-icons@latest/icons";

export function normalizeLanguageName(languageName: string): string {
  return languageName.trim().toLowerCase().replace(/\s+/g, " ");
}

export function getLanguageIcon(languageName: string): string | null {
  if (!languageName?.trim()) return null;

  const key = normalizeLanguageName(languageName);
  const slug = LANGUAGE_ICON_SLUGS[key] ?? FALLBACK_ICON_SLUGS[key] ?? null;
  if (!slug) return null;

  return `${CDN_BASE}/${slug}.svg`;
}

export const LANGUAGE_ICON_MIN_PCT = 15;
