import type { CatalogDefinition, CatalogNode, NodeStatus } from "@/lib/project-index/types";

function n(node: Omit<CatalogNode, "status"> & { status?: NodeStatus }): CatalogNode {
  return {
    ...node,
    status: "implemented",
    aliases: node.aliases ?? [],
    depends_on: node.depends_on ?? [],
    entrypoints: node.entrypoints ?? [],
    paths: node.paths ?? [],
  };
}

export class Catalog {
  static definition(): CatalogDefinition {
    return {
      project: {
        id: "yearongit",
        name: "YearOnGit",
        summary:
          "Wrapped anual de GitHub: OAuth, stats GraphQL, slides, shares y profile cards.",
      },
      scan_roots: [
        "src",
        "prisma",
        "docs",
        "public",
        "package.json",
        "vercel.json",
        "README.md",
        ".env.example",
        "AGENTS.md",
        "tsconfig.json",
        "next.config.ts",
      ],
      ignore: [
        "node_modules",
        ".next",
        "out",
        "build",
        "coverage",
        ".vercel",
        ".git",
        ".project/fingerprints.json",
        ".project/metadata.json",
        ".project/overview.json",
        ".project/index.json",
        ".project/graph.json",
        ".project/filemap.json",
        "src/generated",
      ],
      nodes: Catalog.nodes(),
    };
  }

  static nodes(): CatalogNode[] {
    return [
      n({
        id: "yearongit",
        type: "project",
        name: "YearOnGit",
        parent: null,
        summary: "Aplicación monolítica Next.js del Wrapped de GitHub.",
        paths: [],
        entrypoints: ["src/app/page.tsx", "src/app/layout.tsx", "package.json"],
        depends_on: [],
        aliases: ["wrapped", "year on git", "yearongit"],
      }),

      n({
        id: "domain.product",
        type: "domain",
        name: "Producto Wrapped",
        parent: "yearongit",
        summary: "Experiencia de usuario: landing, loading, slides, share y cards.",
        paths: [],
        entrypoints: [],
        depends_on: [],
        aliases: ["producto", "wrapped product"],
      }),
      n({
        id: "domain.integrations",
        type: "domain",
        name: "Integraciones",
        parent: "yearongit",
        summary: "Auth GitHub, cliente GraphQL y persistencia Postgres/Prisma.",
        paths: [],
        entrypoints: [],
        depends_on: [],
        aliases: ["oauth", "github", "database", "neon"],
      }),
      n({
        id: "domain.platform",
        type: "domain",
        name: "Plataforma",
        parent: "yearongit",
        summary: "i18n, SEO, cookies, legal, errores, UI compartida y audio.",
        paths: [],
        entrypoints: [],
        depends_on: [],
        aliases: ["plataforma", "cross-cutting"],
      }),
      n({
        id: "domain.admin",
        type: "domain",
        name: "Administración",
        parent: "yearongit",
        summary: "Panel y APIs internas de configuración del Wrapped.",
        paths: [],
        entrypoints: [],
        depends_on: [],
        aliases: ["admin", "panel", "mantenimiento"],
      }),
      n({
        id: "domain.tooling",
        type: "domain",
        name: "Tooling",
        parent: "yearongit",
        summary: "Índice de inteligencia, docs, config de build y artefactos públicos.",
        paths: [],
        entrypoints: [],
        depends_on: [],
        aliases: ["tooling", "docs", "config"],
      }),

      n({
        id: "feature.app-shell",
        type: "feature",
        name: "App shell",
        parent: "domain.product",
        summary: "Layout raíz, providers globales y superficies de error de Next.",
        paths: [
          "src/app/layout.tsx",
          "src/app/globals.css",
          "src/app/error.tsx",
          "src/app/global-error.tsx",
          "src/app/not-found.tsx",
          "src/app/forbidden.tsx",
          "src/app/unauthorized.tsx",
          "src/providers/",
        ],
        entrypoints: [
          "src/app/layout.tsx",
          "src/providers/app-provider.tsx",
          "src/app/globals.css",
        ],
        depends_on: [
          "feature.auth",
          "feature.consent",
          "feature.i18n",
          "feature.errors",
        ],
        aliases: ["layout", "providers", "shell"],
      }),
      n({
        id: "feature.landing",
        type: "feature",
        name: "Landing",
        parent: "domain.product",
        summary: "Página de bienvenida y CTAs para iniciar el Wrapped.",
        paths: [
          "src/app/page.tsx",
          "src/components/landing/",
          "src/lib/wrapped/landing-preview-stats.ts",
        ],
        entrypoints: [
          "src/app/page.tsx",
          "src/components/landing/landing-page.tsx",
          "src/components/landing/landing-hero.tsx",
        ],
        depends_on: ["feature.auth", "feature.i18n", "feature.brand-ui"],
        aliases: ["home", "welcome", "inicio"],
      }),
      n({
        id: "feature.info-pages",
        type: "feature",
        name: "How it works y FAQ",
        parent: "domain.product",
        summary: "Páginas informativas de producto fuera de la landing.",
        paths: [
          "src/app/how-it-works/",
          "src/app/faq/",
          "src/components/info/",
        ],
        entrypoints: [
          "src/app/how-it-works/page.tsx",
          "src/app/faq/page.tsx",
          "src/components/info/how-it-works-page.tsx",
          "src/components/info/faq-page.tsx",
        ],
        depends_on: ["feature.i18n", "feature.seo"],
        aliases: ["faq", "how it works", "cómo funciona"],
      }),
      n({
        id: "feature.loading",
        type: "feature",
        name: "Loading del Wrapped",
        parent: "domain.product",
        summary: "Pantalla que solicita stats y prepara la transición a slides.",
        paths: ["src/app/loading/", "src/components/loading/"],
        entrypoints: [
          "src/app/loading/page.tsx",
          "src/components/loading/loading-screen.tsx",
        ],
        depends_on: ["feature.wrapped-stats", "feature.auth"],
        aliases: ["loading", "cargando"],
      }),
      n({
        id: "feature.wrapped-stats",
        type: "feature",
        name: "Cálculo de WrappedStats",
        parent: "domain.product",
        summary: "Fetch GraphQL, normalización y cálculo de estadísticas del año.",
        paths: [
          "src/app/api/wrapped/",
          "src/lib/wrapped/build-stats.ts",
          "src/lib/wrapped/build-stats.test.ts",
          "src/lib/wrapped/fetch-viewer-wrapped.ts",
          "src/lib/wrapped/types.ts",
          "src/lib/wrapped/year.ts",
          "src/lib/wrapped/data-sources.ts",
          "src/lib/wrapped/format.ts",
          "src/lib/wrapped/format-highlight.ts",
          "src/lib/wrapped/contribution-insights.ts",
          "src/lib/wrapped/contribution-insights.test.ts",
          "src/lib/wrapped/heatmap-story.ts",
          "src/lib/wrapped/heatmap-story.test.ts",
          "src/lib/wrapped/weekday-insights.ts",
          "src/lib/wrapped/weekday-insights.test.ts",
          "src/lib/wrapped/favorite-repo-race.ts",
          "src/lib/wrapped/favorite-repo-race.test.ts",
          "src/lib/wrapped/language-icons.ts",
          "src/lib/wrapped/language-icons.test.ts",
          "src/lib/wrapped/languages-available.test.ts",
          "src/lib/wrapped/profile-stats.ts",
          "src/lib/wrapped/profile-stats.test.ts",
          "src/lib/wrapped/random-stats.ts",
          "src/lib/wrapped/plan-slides.ts",
          "src/lib/wrapped/plan-slides.test.ts",
          "src/lib/wrapped/slide-timing.ts",
          "src/lib/wrapped/achievements-catalog.ts",
          "src/lib/wrapped/modules/",
          "src/lib/wrapped/storage.ts",
          "src/lib/wrapped/use-wrapped-stats.ts",
          "src/lib/wrapped/use-random-wrapped-stats.ts",
        ],
        entrypoints: [
          "src/app/api/wrapped/route.ts",
          "src/lib/wrapped/fetch-viewer-wrapped.ts",
          "src/lib/wrapped/build-stats.ts",
          "src/lib/wrapped/plan-slides.ts",
          "src/lib/wrapped/types.ts",
        ],
        depends_on: ["feature.github-api", "feature.auth", "service.db"],
        aliases: [
          "stats",
          "wrappedstats",
          "build-stats",
          "contribuciones",
          "rachas",
          "lenguajes",
          "highlights",
          "achievements",
        ],
      }),
      n({
        id: "feature.wrapped-player",
        type: "feature",
        name: "Player de slides",
        parent: "domain.product",
        summary: "UI cinematográfica que renderiza el plan de slides del Wrapped.",
        paths: [
          "src/app/wrapped/",
          "src/components/wrapped/",
          "src/lib/wrapped/wrapped-ui.tsx",
          "src/lib/wrapped/burst-confetti.ts",
          "src/lib/wrapped/use-stories-navigation.ts",
          "src/lib/wrapped/use-swipe-navigation.ts",
          "src/lib/wrapped/use-prefers-reduced-motion.ts",
        ],
        entrypoints: [
          "src/app/wrapped/page.tsx",
          "src/components/wrapped/wrapped-experience.tsx",
          "src/components/wrapped/shared-wrapped-experience.tsx",
          "src/lib/wrapped/plan-slides.ts",
        ],
        depends_on: [
          "feature.wrapped-stats",
          "feature.share",
          "feature.profile-card",
          "feature.i18n",
        ],
        aliases: ["slides", "player", "wrapped ui", "heatmap", "streak"],
      }),
      n({
        id: "feature.share",
        type: "feature",
        name: "Shares públicos",
        parent: "domain.product",
        summary: "Snapshot público de stats y ruta /share/[slug].",
        paths: [
          "src/app/api/share/",
          "src/app/share/",
          "src/lib/wrapped/share.ts",
          "src/lib/wrapped/share.test.ts",
          "src/lib/wrapped/load-share.ts",
          "src/lib/wrapped/ensure-share-client.ts",
          "src/components/wrapped/share-copy-button.tsx",
          "src/components/wrapped/share-markdown-button.tsx",
        ],
        entrypoints: [
          "src/app/api/share/route.ts",
          "src/app/share/[slug]/page.tsx",
          "src/lib/wrapped/share.ts",
          "src/lib/wrapped/load-share.ts",
        ],
        depends_on: ["feature.wrapped-stats", "service.db", "feature.auth"],
        aliases: ["share", "compartir", "slug", "wrappedshare"],
      }),
      n({
        id: "feature.profile-card",
        type: "feature",
        name: "Profile Card",
        parent: "domain.product",
        summary: "Imagen year-scoped, Markdown README y refresh vía cron.",
        paths: [
          "src/app/api/profile-card/",
          "src/app/api/cron/refresh-profile-cards/",
          "src/app/cards/",
          "src/lib/profile-card/",
        ],
        entrypoints: [
          "src/app/api/profile-card/route.ts",
          "src/lib/profile-card/store.ts",
          "src/lib/profile-card/refresh.ts",
          "src/lib/profile-card/card-image.tsx",
          "src/app/api/cron/refresh-profile-cards/route.ts",
        ],
        depends_on: [
          "feature.wrapped-stats",
          "feature.github-api",
          "service.db",
          "feature.auth",
        ],
        aliases: [
          "profile card",
          "tarjeta",
          "readme card",
          "cron",
          "markdown",
        ],
      }),
      n({
        id: "feature.live-status",
        type: "feature",
        name: "Estado live",
        parent: "domain.product",
        summary: "Endpoint público de estado del producto para clientes.",
        paths: ["src/app/api/live/"],
        entrypoints: ["src/app/api/live/route.ts"],
        depends_on: ["service.db"],
        aliases: ["live", "status", "health público"],
      }),

      n({
        id: "feature.auth",
        type: "feature",
        name: "GitHub OAuth",
        parent: "domain.integrations",
        summary: "Auth.js + proveedor GitHub; sesión y token solo en servidor.",
        paths: [
          "src/auth.ts",
          "src/lib/auth/",
          "src/app/api/auth/",
          "src/app/auth/",
          "src/types/next-auth.d.ts",
          "src/providers/auth-session-provider.tsx",
          "src/providers/auth-session-provider-server.tsx",
        ],
        entrypoints: [
          "src/auth.ts",
          "src/app/api/auth/[...nextauth]/route.ts",
          "src/lib/auth/session.ts",
        ],
        depends_on: ["service.db"],
        aliases: ["oauth", "login", "sesión", "next-auth", "auth.js"],
      }),
      n({
        id: "feature.github-api",
        type: "feature",
        name: "GitHub GraphQL",
        parent: "domain.integrations",
        summary: "Cliente y queries GraphQL de actividad del año.",
        paths: ["src/lib/github/"],
        entrypoints: ["src/lib/github/client.ts", "src/lib/github/queries.ts"],
        depends_on: ["feature.auth"],
        aliases: ["graphql", "contributionscollection", "github api"],
      }),
      n({
        id: "service.db",
        type: "service",
        name: "Prisma / Neon Postgres",
        parent: "domain.integrations",
        summary: "Cliente Prisma y schema de sesiones, shares y cards.",
        paths: ["src/lib/db.ts", "prisma/"],
        entrypoints: ["src/lib/db.ts", "prisma/schema.prisma"],
        depends_on: [],
        aliases: ["prisma", "neon", "postgres", "database", "db"],
      }),

      n({
        id: "feature.i18n",
        type: "feature",
        name: "Internacionalización",
        parent: "domain.platform",
        summary: "Locales, traducciones y helpers de UI multi-idioma.",
        paths: ["src/lib/i18n/", "src/components/i18n/"],
        entrypoints: [
          "src/lib/i18n/translations.ts",
          "src/lib/i18n/supported-locales.ts",
          "src/lib/i18n/use-view-i18n.ts",
        ],
        depends_on: [],
        aliases: ["i18n", "locales", "traducciones", "idioma"],
      }),
      n({
        id: "feature.seo",
        type: "feature",
        name: "SEO",
        parent: "domain.platform",
        summary: "Metadata de páginas, sitemap, robots y JSON-LD/GA.",
        paths: [
          "src/lib/seo/",
          "src/components/seo/",
          "src/app/robots.ts",
          "src/app/sitemap.ts",
          "src/lib/app-url.ts",
          "docs/SEO.md",
          "public/llms.txt",
        ],
        entrypoints: [
          "src/lib/seo/pages.ts",
          "src/app/sitemap.ts",
          "src/app/robots.ts",
          "src/lib/app-url.ts",
        ],
        depends_on: [],
        aliases: ["seo", "sitemap", "robots", "metadata", "llms"],
      }),
      n({
        id: "feature.consent",
        type: "feature",
        name: "Consentimiento de cookies",
        parent: "domain.platform",
        summary: "Preferencias de cookies y activación condicional de analítica.",
        paths: [
          "src/lib/consent/",
          "src/providers/consent-provider.tsx",
          "src/components/legal/cookie-consent-banner.tsx",
        ],
        entrypoints: [
          "src/lib/consent/cookies.ts",
          "src/providers/consent-provider.tsx",
          "src/components/legal/cookie-consent-banner.tsx",
        ],
        depends_on: ["feature.seo"],
        aliases: ["cookies", "consent", "gdpr", "analítica"],
      }),
      n({
        id: "feature.legal",
        type: "feature",
        name: "Privacidad y términos",
        parent: "domain.platform",
        summary: "Contenido y páginas legales EN/ES.",
        paths: [
          "src/lib/legal/",
          "src/components/legal/legal-page.tsx",
          "src/app/privacy/",
          "src/app/terms/",
          "docs/PRIVACY-COOKIES.md",
        ],
        entrypoints: [
          "src/lib/legal/content.ts",
          "src/app/privacy/page.tsx",
          "src/app/terms/page.tsx",
        ],
        depends_on: ["feature.i18n"],
        aliases: ["privacy", "terms", "legal", "privacidad", "términos"],
      }),
      n({
        id: "feature.errors",
        type: "feature",
        name: "Errores y resiliencia",
        parent: "domain.platform",
        summary: "Catálogo de errores, pantallas y utilidades de reintento.",
        paths: [
          "src/lib/errors/",
          "src/components/error/",
          "src/app/errors/",
        ],
        entrypoints: [
          "src/lib/errors/catalog.ts",
          "src/lib/errors/app-error.ts",
          "src/components/error/error-screen.tsx",
          "src/app/errors/[code]/page.tsx",
        ],
        depends_on: [],
        aliases: ["errors", "errores", "resilience", "retry"],
      }),
      n({
        id: "feature.brand-ui",
        type: "feature",
        name: "Brand, layout y UI",
        parent: "domain.platform",
        summary: "Marca, shell de página, header/footer y primitivas visuales.",
        paths: [
          "src/lib/brand/",
          "src/components/brand/",
          "src/components/layout/",
          "src/components/ui/",
          "public/brand/",
        ],
        entrypoints: [
          "src/components/layout/page-shell.tsx",
          "src/components/layout/glass-header.tsx",
          "src/components/brand/brand-wordmark.tsx",
          "src/lib/brand/assets.ts",
        ],
        depends_on: ["feature.i18n", "feature.audio"],
        aliases: ["ui", "brand", "header", "footer", "page-shell"],
      }),
      n({
        id: "feature.audio",
        type: "feature",
        name: "Audio / SFX",
        parent: "domain.platform",
        summary: "Motor de efectos de sonido y provider de mute.",
        paths: [
          "src/lib/audio/",
          "src/providers/sfx-provider.tsx",
          "src/components/layout/sound-toggle.tsx",
        ],
        entrypoints: [
          "src/lib/audio/sfx-engine.ts",
          "src/providers/sfx-provider.tsx",
        ],
        depends_on: [],
        aliases: ["sfx", "sound", "audio"],
      }),
      n({
        id: "feature.http",
        type: "feature",
        name: "HTTP helpers",
        parent: "domain.platform",
        summary: "Respuestas API y fetch JSON tipado para el cliente.",
        paths: ["src/lib/http/"],
        entrypoints: [
          "src/lib/http/api-response.ts",
          "src/lib/http/fetch-json.ts",
        ],
        depends_on: [],
        aliases: ["http", "fetch", "api-response"],
      }),

      n({
        id: "feature.admin-panel",
        type: "feature",
        name: "Panel admin",
        parent: "domain.admin",
        summary: "UI de administración y preview de slides/config.",
        paths: ["src/app/admin/", "src/components/admin/"],
        entrypoints: [
          "src/app/admin/page.tsx",
          "src/components/admin/admin-panel.tsx",
          "src/app/admin/preview/page.tsx",
        ],
        depends_on: ["feature.admin-api", "feature.auth"],
        aliases: ["admin ui", "preview admin"],
      }),
      n({
        id: "feature.admin-api",
        type: "feature",
        name: "API y librería admin",
        parent: "domain.admin",
        summary: "Route Handlers y lógica de acceso/config/auditoría admin.",
        paths: ["src/app/api/admin/", "src/lib/admin/"],
        entrypoints: [
          "src/lib/admin/require-admin.ts",
          "src/lib/admin/access.ts",
          "src/lib/admin/wrapped-config.ts",
          "src/lib/admin/settings.ts",
        ],
        depends_on: ["feature.auth", "service.db", "feature.wrapped-stats"],
        aliases: [
          "admin api",
          "allowlist",
          "wrapped-config",
          "audit",
          "maintenance",
        ],
      }),

      n({
        id: "infrastructure.project-index",
        type: "infrastructure",
        name: "Project Intelligence Index",
        parent: "domain.tooling",
        summary: "Catálogo, indexer y CLI de navegación para agentes.",
        paths: [
          "src/lib/project-index/",
          ".project/README.md",
          ".githooks/",
        ],
        entrypoints: [
          "src/lib/project-index/catalog.ts",
          "src/lib/project-index/indexer.ts",
          "src/lib/project-index/index-query.ts",
          "src/lib/project-index/cli/index-cmd.ts",
          "src/lib/project-index/cli/query-cmd.ts",
        ],
        depends_on: [],
        aliases: [
          "project index",
          "intelligence",
          "índice",
          "catalog",
          "stale",
        ],
      }),
      n({
        id: "configuration.app",
        type: "configuration",
        name: "Configuración de app",
        parent: "domain.tooling",
        summary: "package.json, Next, env de ejemplo, Vercel cron y tsconfig.",
        paths: [
          "package.json",
          "tsconfig.json",
          "next.config.ts",
          "vercel.json",
          ".env.example",
        ],
        entrypoints: ["package.json", "vercel.json", ".env.example"],
        depends_on: [],
        aliases: ["config", "env", "vercel", "cron config"],
      }),
      n({
        id: "documentation.root",
        type: "documentation",
        name: "Documentación",
        parent: "domain.tooling",
        summary: "README, reglas de agentes y docs de SEO/privacidad.",
        paths: ["README.md", "AGENTS.md", "docs/", "public/llms.txt"],
        entrypoints: ["README.md", "AGENTS.md"],
        depends_on: [],
        aliases: ["readme", "docs", "agents"],
      }),
      n({
        id: "infrastructure.static-assets",
        type: "infrastructure",
        name: "Assets estáticos",
        parent: "domain.tooling",
        summary: "Favicon, OG e iconos públicos fuera de brand.",
        paths: ["public/"],
        entrypoints: ["public/llms.txt"],
        depends_on: [],
        aliases: ["public", "assets", "favicon"],
      }),
      n({
        id: "test.suites",
        type: "test",
        name: "Suites de test",
        parent: "domain.tooling",
        summary: "Tests unitarios ejecutados con tsx --test.",
        paths: [],
        entrypoints: ["package.json"],
        depends_on: [],
        aliases: ["tests", "tsx test"],
      }),
    ];
  }
}
