export const ERROR_CODES = {
  AUTHENTICATION: "AUTHENTICATION",
  AUTHORIZATION: "AUTHORIZATION",
  RATE_LIMIT: "GITHUB_RATE_LIMIT",
  GITHUB_API: "GITHUB_API",
  NETWORK: "NETWORK",
  TIMEOUT: "TIMEOUT",
  VALIDATION: "VALIDATION",
  DATA_UNAVAILABLE: "DATA_UNAVAILABLE",
  NOT_FOUND: "NOT_FOUND",
  UNKNOWN: "UNKNOWN",
} as const;

export type AppErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
